const actionTypes = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  LOAD_ORDER_PRODUCTS: 'LOAD_ORDER_PRODUCTS',
  LOAD_ORDER_PRODUCTS_ERROR: 'LOAD_ORDER_PRODUCTS_ERROR',
};

export default actionTypes;
