const actionTypes = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  LOAD_ORDER_PRODUCTS: 'LOAD_ORDER_PRODUCTS',
  LOAD_ORDER_PRODUCTS_ERROR: 'LOAD_ORDER_PRODUCTS_ERROR',
  ADD_TO_ORDER: 'ADD_TO_ORDER',
  ADD_TO_ORDER_ERROR: 'ADD_TO_ORDER_ERROR',
  DELETE_FROM_ORDER: 'DELETE_FROM_ORDER',
  DELETE_FROM_ORDER_ERROR: 'DELETE_FROM_ORDER_ERROR',
  ADD_USER: 'ADD_USER',
  ADD_USER_ERROR: 'ADD_USER_ERROR',
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
};

export default actionTypes;
