const actionTypes = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  LOAD_ORDER_PRODUCTS: 'LOAD_ORDER_PRODUCTS',
  LOAD_ORDER_PRODUCTS_ERROR: 'LOAD_ORDER_PRODUCTS_ERROR',
  ADD_TO_ORDER: 'ADD_TO_ORDER',
  ADD_TO_ORDER_ERROR: 'ADD_TO_ORDER_ERROR',
  DELETE_FROM_ORDER: 'DELETE_FROM_ORDER',
  DELETE_FROM_ORDER_ERROR: 'DELETE_FROM_ORDER_ERROR',
  LOGIN_USER_GOOGLE: 'LOGIN_USER_GOOGLE',
  LOGIN_USER_GOOGLE_ERROR: 'LOGIN_USER_GOOGLE_ERROR',
  SEND_USER: 'SEND_USER',
  SEND_USER_ERROR: 'SEND_USER_ERROR',
  LOGOUT_USER: 'LOGOUT_USER',
};

export default actionTypes;
