import stylesType from '../../../styles/stylesType';

const OrderStyles = {
  titleContainer: {
    margin: 20,
  },
  title: {
    fontSize: 30,
    fontWeight: '700',
    textAlign: 'center',
    color: stylesType.black,

  },
  body: {
    display: 'flex',
    justifyContent: 'center',
    flex: 1,
    flexDirection: 'column',
    margin: 0,
    height: 'auto',
    width: '100%',
    flexGrow: 1,
  },
  container: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    height: 'auto',
    flexGrow: 1,
    flex: 1,
    margin: 10,
  },
  productInfo: {
    marginLeft: 10,
    flex: 1,
  },
  productView: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    padding: 10,
    backgroundColor: '#FFF',
  },
  list: {
    display: 'flex',
    flexDirection: 'row',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    margin: 10,
    marginTop: 20,
  },
  item: {
    backgroundColor: '#202020',
    margin: 10,
  },
  productTitle: {
    color: stylesType.black,
    fontSize: 16,
    fontWeight: 'bold',
  },
  price: {
    color: '#CD3B3B',
  },
  imageContainer: {
    height: 100,
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 10,
    marginTop: -10,
  },
  image: {
    position: 'relative',
    resizeMode: 'contain',
    height: 100,
  },
  buttons: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  button: {
    backgroundColor: stylesType.brown,
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: 20,
    margin: 10,
  },
  quantity: {
    fontSize: 30,
    color: stylesType.black,
  },
  totalSentProduct: {
    fontSize: 22,
    color: stylesType.black,
  },
  submit: {
    height: 90,
    padding: 0.5,
    paddingBottom: 15,
    backgroundColor: stylesType.brown,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  submitTouchable: {
    height: '100%',
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    margin: 5,
  },
  submitText: {
    color: 'white',
    fontSize: 22,
    fontWeight: '600',
    margin: 5,
  },
  paymentButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#27AE60',
    padding: 2,
    borderRadius: 20,
    margin: 0,
  },
  paymentImage: {
    width: 32,
    height: 32,
  },
  totalContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    marginBottom: 20,
    padding: 15,
    justifyContent: 'space-between',
  },
  totalTextAndNumber: {
    display: 'flex',
    flexDirection: 'row',
    padding: 10,
  },
  totalText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#202020',
    marginRight: 10,
  },
  noOrder: {
    margin: 40,
    fontSize: 16,
    color: stylesType.black,
    textAlign: 'center',
  },
  totalAmount: {
    fontSize: 20,
    fontWeight: '600',
    color: '#202020',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.9,
    shadowRadius: 300,
    elevation: 5,
  },
  closeButton: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  modalContent: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 30,
  },
  textStyle: {
    alignItems: 'center',
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    fontSize: 22,
    textAlign: 'center',
  },
  modalImage: {
    marginTop: 20,
    height: 80,
    width: 80,
  },
  yesNoContainer: {
    display: 'flex',
    flexDirection: 'row',
    margin: 20,
  },
  yesNoButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: 35,
    width: 80,
    paddingHorizontal: 25,
    backgroundColor: stylesType.brown,
    marginHorizontal: 20,
    borderRadius: 30,
  },
  yesNoText: {
    fontSize: 22,
    color: 'white',
  },
};

export default OrderStyles;
